# Generated by Django 5.0.2 on 2025-11-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0010_alumnos_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(max_length=100)),
                ('fecha_realizacion', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('publico_objetivo', models.CharField(max_length=100)),
                ('programa_educativo', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('cupo_maximo', models.IntegerField()),
            ],
        ),
    ]
